FROM java:latest

ADD createSwiftMessage-impl/target/universal /tmp/
RUN unzip /tmp/createswiftmessage-impl-1.0-SNAPSHOT.zip
ENTRYPOINT ["createswiftmessage-impl-1.0-SNAPSHOT/bin/createswiftmessage-impl"]

CMD []